const degToRadians = (deg) => (deg * Math.PI) / 180;

// General constants.
const PI = Math.PI;
const TWO_PI = PI;

const SCREEN_WIDTH = 1080;//1024//854;//window.innerWidth;
const SCREEN_HEIGHT = 768;//768//480;// window.innerHeight;
const HALF_SCREEN_WIDTH = SCREEN_WIDTH / 2;
const HALF_SCREEN_HEIGHT = SCREEN_HEIGHT / 2;
const HALF_SCREEN_WIDTH_FLOORED = Math.floor(HALF_SCREEN_WIDTH);
const HALF_SCREEN_HEIGHT_FLOORED = Math.floor(HALF_SCREEN_HEIGHT);
const GAME_LOOP_TICK_MS = 20;
const MINIMAP_BASE_POSITION_X = 5;
const MINIMAP_BASE_POSITION_Y = 5;
const MINIMAP_SCALE = 0.10;
const FIELD_OF_VIEW = degToRadians(72);
const HALF_FIELD_OF_VIEW = FIELD_OF_VIEW / 2;
const ANGLE_BETWEEN_RAYS = FIELD_OF_VIEW / SCREEN_WIDTH; // One ray is cast per vertical column of screen pixels.
const MINIMAP_PLAYER_SIZE = 10;
const CELL_SIZE = 256;
const PLAYER_WALK_SPEED = 8;
const PLAYER_ANGULAR_SPEED_DEGREES = 3;
const PLAYER_CLIP_DETECTION_DISTANCE = PLAYER_WALK_SPEED + 1;
const PLAYER_DISTANCE_TO_PROJECTION_PLANE = (HALF_SCREEN_WIDTH) / Math.tan(HALF_FIELD_OF_VIEW);
const PLAYER_HEIGHT = Math.floor(CELL_SIZE / 2);

const colours = Object.freeze({
  CELL: 'grey',
  MINIMAP_PLAYER: 'white',
  RAYS: '#ffa600',
  FLOOR: "#d52b1e", // "#ff6361"
  CEILING: '#3C3C3C', // "#012975",
  WALL: "#013aa6", // "#58508d"
  WALL_DARK: "#012975", // "#003f5c"
});

module.exports = Object.freeze({
  PI,
  TWO_PI,
  SCREEN_WIDTH,
  SCREEN_HEIGHT,
  HALF_SCREEN_WIDTH,
  HALF_SCREEN_HEIGHT,
  HALF_SCREEN_WIDTH_FLOORED,
  HALF_SCREEN_HEIGHT_FLOORED,
  GAME_LOOP_TICK_MS,
  MINIMAP_BASE_POSITION_X,
  MINIMAP_BASE_POSITION_Y,
  MINIMAP_SCALE,
  FIELD_OF_VIEW,
  HALF_FIELD_OF_VIEW,
  ANGLE_BETWEEN_RAYS,
  MINIMAP_PLAYER_SIZE,
  CELL_SIZE,
  PLAYER_WALK_SPEED,
  PLAYER_ANGULAR_SPEED_DEGREES,
  PLAYER_CLIP_DETECTION_DISTANCE,
  PLAYER_DISTANCE_TO_PROJECTION_PLANE,
  PLAYER_HEIGHT,
  colours,
});